<section class="h-screen w-full">
    <?php if (isset($film)): ?>
        <h1 class="font-bold p-3 border-b-2 border-neutral-900 text-center text-2xl">FILMS DETAILS</h1>
        <ul class="p-3">
            <li>Title: <?= htmlspecialchars($film['title']) ?></li>
            <li>Opening crawl: <?= htmlspecialchars($film['opening_crawl']) ?></li>
            <li>Director: <?= htmlspecialchars($film['director']) ?></li>
            <li>Producer: <?= htmlspecialchars($film['producer']) ?></li>
            <li>Release date: <?= htmlspecialchars($film['release_date']) ?></li>
        </ul>
    <?php elseif (isset($films_list) && is_array($films_list)): ?>
        <h1 class="font-bold p-3 border-b-2 border-neutral-900 text-center text-2xl">FILMS LIST</h1>
        <ul class="p-3">
            <?php foreach ($films_list['results'] as $films): ?>
                <?php
                if (isset($films['url']) && !empty($films['url'])) {
                    $url = $films['url'];
                    $lastSlashPos = strrpos($url, '/', -2);
                    $id = substr($url, $lastSlashPos + 1, -1);
                } else {
                    $id = 1;
                }
                ?>
                <li><a href="<?= BASE_URL ?>/films/<?= htmlspecialchars($id) ?>"><?= htmlspecialchars($films['title']) ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p>No data available.</p>
    <?php endif; ?>
</section>
</html>
