<?php

require_once BASE_PATH . '/app/controllers/people_controller.php';

?>

<section>
    <?php if (isset($person)): ?>
        <h1 class="font-bold mb-5 text-2xl">Person Details</h1>
        <ul>
            <li>Name: <?= htmlspecialchars($person['name']) ?></li>
            <li>Height: <?= htmlspecialchars($person['height']) ?></li>
            <li>Mass: <?= htmlspecialchars($person['mass']) ?></li>
            <li>Hair color: <?= htmlspecialchars($person['hair_color']) ?></li>
            <li>Skin color: <?= htmlspecialchars($person['skin_color']) ?></li>
            <li>Eye color: <?= htmlspecialchars($person['eye_color']) ?></li>
            <li>Hair color: <?= htmlspecialchars($person['hair_color']) ?></li>
            <li>Birth year: <?= htmlspecialchars($person['birth_year']) ?></li>
            <li>Gender: <?= htmlspecialchars($person['gender']) ?></li>
        </ul>
    <?php elseif (isset($person_list) && is_array($person_list)): ?>
        <h1 class="font-bold mb-5 text-2xl">People List</h1>
        <ul>
            <?php foreach ($person_list['results'] as $person): ?>
                <?php
                if (isset($person['url']) && !empty($person['url'])) {
                    $url = $person['url'];
                    $lastSlashPos = strrpos($url, '/', -2);
                    $id = substr($url, $lastSlashPos + 1, -1);
                } else {
                    $id = 1;
                }
                ?>
                <li><a href="<?= BASE_URL ?>/people/<?= htmlspecialchars($id) ?>"><?= htmlspecialchars($person['name']) ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p>No data available.</p>
    <?php endif; ?>
</section>