<section>
    <?php if (isset($person)): ?>
        <h1 class="font-bold p-3 border-b-2 border-neutral-900 text-center text-2xl">PERSON DETAILS</h1>
        <div class="flex flex-col items-center justify-evenly h-full">
            <article class="my-7 bg-neutral-900 p-5 rounded-md flex gap-5">
                <div class="flex justify-evenly items-center">
                    <img src="<?= isset($person['image']) ? htmlspecialchars($person['image']) : '../public/assets/images/unknown.png' ?>" width="200px" alt="<?= htmlspecialchars($person['name']) ?>">
                </div>
                <ul>
                    <li class="text-xl mb-5 font-bold"><?= ucfirst(htmlspecialchars($person['name'])) ?></li>
                    <li>Height: <?= ucfirst(htmlspecialchars($person['height'])) ?></li>
                    <li>Mass: <?= ucfirst(htmlspecialchars($person['mass'])) ?></li>
                    <li>Hair color: <?= ucfirst(htmlspecialchars($person['hair_color'])) ?></li>
                    <li>Skin color: <?= ucfirst(htmlspecialchars($person['skin_color'])) ?></li>
                    <li>Eye color: <?= ucfirst(htmlspecialchars($person['eye_color'])) ?></li>
                    <li>Hair color: <?= ucfirst(htmlspecialchars($person['hair_color'])) ?></li>
                    <li>Birth year: <?= ucfirst(htmlspecialchars($person['birth_year'])) ?></li>
                    <li>Gender: <?= ucfirst(htmlspecialchars($person['gender'])) ?></li>
                </ul>
                <div class="h-[240px] w-[2px] bg-neutral-700 rounded-md"></div>
                <div class="h-full">
                    <h2 class="font-bold text-lg mb-5 text-center">Films</h2>
                    <ul>
                        <?php if (!empty($person['films'])): ?>
                            <?php foreach ($person['films'] as $film): ?>
                                <li><a href="<?= BASE_URL . '/films'. '/' . htmlspecialchars(basename($film)) ?>" class="text-blue-500 underline">Film <?= htmlspecialchars(basename($film)) ?></a></li>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <li>No data</li>
                        <?php endif; ?>
                    </ul>
                </div>
                <div class="h-[240px] w-[2px] bg-neutral-700 rounded-md"></div>
                <div class="h-full">
                    <h2 class="font-bold text-lg mb-5 text-center">Homeworld</h2>
                    <ul>
                        <?php if (!empty($person['homeworld'])): ?>
                            <li><a href="<?= BASE_URL . '/planets' .'/' . htmlspecialchars(basename($person['homeworld'])) ?>" class="text-blue-500 underline">Homeworld <?= htmlspecialchars(basename($person['homeworld'])) ?></a></li>
                        <?php else: ?>
                            <li>No data</li>
                        <?php endif; ?>
                    </ul>
                </div>
                <div class="h-[240px] w-[2px] bg-neutral-700 rounded-md"></div>
                <div class="h-full">
                    <h2 class="font-bold text-lg mb-5 text-center">Vehicles</h2>
                    <ul>
                        <?php if (!empty($person['vehicles'])): ?>
                            <?php foreach ($person['vehicles'] as $vehicles): ?>
                                <li><a href="<?= BASE_URL . '/vehicles' . '/' . htmlspecialchars(basename($vehicles)) ?>" class="text-blue-500 underline">Vehicle <?= htmlspecialchars(basename($vehicles)) ?></a></li>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <li>No data</li>
                        <?php endif; ?>
                    </ul>
                </div>
                <div class="h-[240px] w-[2px] bg-neutral-700 rounded-md"></div>
                <div class="h-full">
                    <h2 class="font-bold text-lg mb-5 text-center">Starships</h2>
                    <ul>
                        <?php if (!empty($person['starships'])): ?>
                            <?php foreach ($person['starships'] as $starships): ?>
                                <li><a href="<?= BASE_URL . '/starships' . '/' . htmlspecialchars(basename($starships)) ?>" class="text-blue-500 underline">Starships <?= htmlspecialchars(basename($starships)) ?></a></li>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <li>No data</li>
                        <?php endif; ?>
                    </ul>
                </div>

            </article>
        </div>
    <?php elseif (isset($person_list) && is_array($person_list)): ?>
        <article>
            <h1 class="font-bold p-3 border-b-2 border-neutral-900 text-center text-2xl">PEOPLE LIST</h1>
            <ul class="p-3">
                <?php foreach ($person_list['results'] as $person): ?>
                    <?php
                    if (isset($person['url']) && !empty($person['url'])) {
                        $url = $person['url'];
                        $last_slash_pos = strrpos($url, '/', -2);
                        $id = substr($url, $last_slash_pos + 1, -1);
                    } else {
                        $id = 1;
                    }
                    ?>
                    <li><a href="<?= BASE_URL ?>/people/<?= htmlspecialchars($id) ?>"><?= htmlspecialchars($person['name']) ?></a></li>
                <?php endforeach; ?>
            </ul>
        </article>
    <?php else: ?>
        <p>No data available.</p>
    <?php endif; ?>
</section>