<section class="h-screen w-full">
    <?php if (isset($planet)): ?>
        <h1 class="font-bold p-3 border-b-2 border-neutral-900 text-center text-2xl">PLANET DETAILS</h1>
        <ul class="p-3">
            <li>Name: <?= htmlspecialchars($planet['name']) ?></li>
            <li>Rotation period: <?= htmlspecialchars($planet['rotation_period']) ?></li>
            <li>Orbital period: <?= htmlspecialchars($planet['orbital_period']) ?></li>
            <li>Diameter: <?= htmlspecialchars($planet['diameter']) ?></li>
            <li>Climate: <?= htmlspecialchars($planet['climate']) ?></li>
            <li>Gravity: <?= htmlspecialchars($planet['gravity']) ?></li>
            <li>Terrain: <?= htmlspecialchars($planet['terrain']) ?></li>
            <li>Surface water: <?= htmlspecialchars($planet['surface_water']) ?></li>
            <li>Population: <?= htmlspecialchars($planet['population']) ?></li>
        </ul>
    <?php elseif (isset($planets_list) && is_array($planets_list)): ?>
        <h1 class="font-bold p-3 border-b-2 border-neutral-900 text-center text-2xl">PLANETS LIST</h1>
        <ul class="p-3">
            <?php foreach ($planets_list['results'] as $planets): ?>
                <?php
                if (isset($planets['url']) && !empty($planets['url'])) {
                    $url = $planets['url'];
                    $lastSlashPos = strrpos($url, '/', -2);
                    $id = substr($url, $lastSlashPos + 1, -1);
                } else {
                    $id = 1;
                }
                ?>
                <li><a href="<?= BASE_URL ?>/planets/<?= htmlspecialchars($id) ?>"><?= htmlspecialchars($planets['name']) ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p>No data available.</p>
    <?php endif; ?>
</section>